packages:
  - '.'
  - 'modules/*'

overrides:
  '@cloudflare/workers-types': ^5.20260712.1
  '@types/node': 24.13.3
  drizzle-orm: 1.0.0-rc.4
  fontless>esbuild: '>=0.28.1'
  unhead: 3.2.1
  '@unhead/vue': 3.2.1
  '@unhead/bundler': 3.2.1

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': false
  better-sqlite3: true
  core-js: false
  esbuild: true
  msw: false
  prisma: false
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@nuxt/kit@4.5.0'
  - '@nuxt/nitro-server@4.5.0'
  - '@nuxt/schema@4.5.0'
  - '@nuxt/vite-builder@4.5.0'
  - nuxt@4.5.0
  - unhead@3.2.1
  - '@unhead/vue@3.2.1'
  - '@unhead/bundler@3.2.1'
