<template>
  <div
    v-if="parts.length"
    ref="containerRef"
    class="overflow-hidden attached-files mb-2"
    role="region"
    :aria-label="`${parts.length === 1 ? 'File' : 'Files'}`"
  >
    <div class="carousel flex gap-2 w-full rounded-box">
      <div
        v-for="file in parts"
        :key="file.displayKey"
        :aria-label="
          file.isHidden
            ? 'Hidden file'
            : `File ${file.filename || 'attachment'}`
        "
        class="group carousel-item relative overflow-hidden flex items-center justify-center size-48 rounded-box aspect-square bg-base-300"
      >
        <Icon
          :name="getFileIcon(file.mediaType)"
          size="48"
          class="z-10 text-base-content/40"
        />
        <div
          v-if="file.isHidden"
          data-testid="chat-file-hidden"
          class="absolute z-20 inset-0 flex flex-col items-center justify-center bg-base-300"
        >
          <Icon
            name="lucide:eye-off"
            size="32"
            class="text-base-content/40"
          />
          <span class="text-xs text-base-content/50 mt-2">
            Hidden
          </span>
        </div>
        <div
          v-else-if="!file.links || failedUrls[file.links.openUrl]"
          data-testid="chat-file-unavailable"
          class="absolute z-20 inset-0 flex flex-col items-center justify-center bg-base-300"
        >
          <Icon
            name="lucide:image-off"
            size="32"
            class="text-base-content/40"
          />
          <span class="text-xs text-base-content/50 mt-2">
            {{ file.links ? 'Not found' : 'Unavailable' }}
          </span>
        </div>
        <button
          v-else-if="file.links && isImageFile(file.mediaType)"
          type="button"
          class="absolute inset-0 z-20 block size-full"
          :class="isImagePreviewSuppressed ? 'cursor-default' : 'cursor-zoom-in'"
          :aria-label="`Preview ${file.filename || 'attached image'}`"
          data-testid="chat-file-preview-trigger"
          @click="openImagePreview(file)"
        >
          <img
            :src="file.links.openUrl"
            :alt="file.filename || 'Attached image'"
            class="block size-full shrink-0 aspect-square object-cover"
            loading="lazy"
            @error="onImageError(file.links.openUrl)"
          >
        </button>
        <div
          v-if="file.links && !failedUrls[file.links.openUrl]"
          class="absolute z-30 top-2 right-2 flex gap-1"
          :class="{
            [
              'md:opacity-0 md:group-hover:opacity-100 '
              + 'md:focus-within:opacity-100 transition-opacity'
            ]: $device.isDesktop,
          }"
        >
          <button
            v-if="isImageFile(file.mediaType)"
            type="button"
            data-testid="chat-file-open"
            class="btn btn-circle btn-xs btn-soft"
            :aria-label="`Preview ${file.filename || 'file'}`"
            title="Preview"
            @click="openImagePreview(file)"
          >
            <Icon name="lucide:maximize-2" size="12" />
          </button>
          <a
            v-else
            :href="file.links.openUrl"
            target="_blank"
            rel="noopener noreferrer"
            data-testid="chat-file-open"
            class="btn btn-circle btn-xs btn-soft"
            :aria-label="`Open ${file.filename || 'file'}`"
            title="Open"
          >
            <Icon name="lucide:external-link" size="12" />
          </a>
          <a
            :href="file.links.downloadUrl"
            data-testid="chat-file-download"
            class="btn btn-circle btn-xs btn-soft"
            :aria-label="`Download ${file.filename || 'file'}`"
            title="Download"
          >
            <Icon name="lucide:download" size="12" />
          </a>
        </div>
        <span
          v-if="file.isGenerated"
          class="badge badge-secondary badge-xs absolute z-30 top-1 left-1 text-2xs leading-none gap-0.5 pointer-events-none"
          aria-label="Generated by AI"
        >
          <Icon name="lucide:sparkles" size="10" />
          AI
        </span>
        <div
          v-if="file.filename"
          :title="file.filename"
          class="absolute z-30 bottom-0 -inset-x-0 py-1 px-2 bg-base-100/90 text-base-content text-xs font-medium truncate"
          :class="{
            [`
              md:transition-transform
              md:translate-y-full
              md:group-hover:translate-y-0
            `]: $device.isDesktop && isImageFile(file.mediaType),
          }"
        >
          {{ truncateFilename(file.filename) }}
        </div>
      </div>
    </div>
    <LazyChatImagePreview
      v-if="isImagePreviewOpen && previewFile?.links"
      v-model:open="isImagePreviewOpen"
      :src="previewFile.links.openUrl"
      :download-url="previewFile.links.downloadUrl"
      :alt="previewFile.filename || 'Attached image'"
      :filename="previewFile.filename || 'Attached image'"
    />
  </div>
</template>

<script setup lang="ts">
import type { UIMessage, FileUIPart } from 'ai'
import type { SafeFileLinks } from '~/utils/files'
import { isGeneratedFilePart, isHiddenFilePart } from '#shared/utils/files'

interface DisplayFile {
  displayKey: string
  filename?: string
  mediaType: FileUIPart['mediaType']
  links: SafeFileLinks | null
  isHidden: boolean
  isGenerated: boolean
}

const props = defineProps<{
  message: UIMessage
}>()

const { isSuppressed: isImagePreviewSuppressed } = useImagePreviewGuard()

const containerRef = useTemplateRef<HTMLDivElement>('containerRef')
const failedUrls = reactive<Record<string, boolean>>({})
const previewFile = shallowRef<DisplayFile | null>(null)
const isImagePreviewOpen = shallowRef<boolean>(false)

const parts = computed<DisplayFile[]>(() => {
  return props.message.parts.flatMap((part, index): DisplayFile[] => {
    if (part.type !== 'file') {
      return []
    }

    if (isHiddenFilePart(part)) {
      return [{
        displayKey: `${index}:hidden`,
        filename: undefined,
        mediaType: part.mediaType,
        links: null,
        isHidden: true,
        isGenerated: false,
      }]
    }

    return [{
      displayKey: `${index}:${part.filename || 'file'}`,
      filename: part.filename,
      mediaType: part.mediaType,
      links: getSafeFileLinks(part.url),
      isHidden: false,
      isGenerated: isGeneratedFilePart(part),
    }]
  })
})

function onImageError(url: string) {
  failedUrls[url] = true

  if (previewFile.value?.links?.openUrl === url) {
    isImagePreviewOpen.value = false
  }
}

function openImagePreview(file: DisplayFile) {
  if (isImagePreviewSuppressed.value) return

  if (!file.links || !isImageFile(file.mediaType)) {
    return
  }

  previewFile.value = file
  isImagePreviewOpen.value = true
}

onMounted(() => {
  if (!containerRef.value) {
    return
  }

  const images = containerRef.value.querySelectorAll('img')

  images.forEach((img) => {
    if (img.complete && img.currentSrc && img.naturalWidth === 0) {
      const imageUrl = img.getAttribute('src')

      if (imageUrl) {
        failedUrls[imageUrl] = true
      }
    }
  })
})
</script>
