import { mountSuspended } from '@nuxt/test-utils/runtime'
import { describe, expect, it } from 'vitest'
import GeneratedImage from '../../../../app/components/Chat/GeneratedImage.vue'

describe('Chat/GeneratedImage', () => {
  it('shows an honest generation phase without a fake percentage', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-available',
          input: { aspectRatio: '3:2' },
          output: { status: 'generating' },
        } as any,
      },
    })

    expect(wrapper.get('[data-testid="generated-image-progress"]').text())
      .toContain('Generating your image')
    expect(wrapper.get('[data-testid="generated-image-progress"]')
      .attributes('style')).toContain('aspect-ratio: 3 / 2')
    expect(wrapper.text()).not.toMatch(/\d+%/)
  })

  it('renders the saved image with provenance and download actions', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-available',
          output: {
            status: 'ready',
            provider: 'google',
            model: 'gemini-3.1-flash-image',
            file: {
              id: 'file-1',
              storageKey: 'generated.webp',
              name: 'sunset.webp',
              size: 2048,
              type: 'image/webp',
              source: 'assistant',
              url: 'javascript:alert(1)',
              downloadUrl: 'javascript:alert(2)',
            },
          },
        } as any,
      },
    })

    const image = wrapper.get('img')
    const links = wrapper.findAll('a')

    expect(wrapper.get('[data-testid="generated-image-ready"]').text())
      .toContain('Generated by AI')
    expect(wrapper.text()).toContain('Google AI')
    expect(image.attributes('src')).toBe('/files/generated.webp')
    expect(links[1]?.attributes('href'))
      .toBe('/files/generated.webp?download=1')

    await image.trigger('load')

    expect(image.classes()).toContain('generated-image--loaded')
  })

  it('renders fixed actionable text for a structured failure', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-error',
          errorText: JSON.stringify({
            code: 'provider-auth',
            message: 'Untrusted provider text',
            fix: 'Open javascript:alert(1)',
            secret: 'sk-never-render-this',
          }),
        } as any,
      },
    })

    const alert = wrapper.get('[data-testid="generated-image-error"]')

    expect(alert.attributes('role')).toBe('alert')
    expect(alert.text()).toContain(
      'The image provider rejected the saved API key.',
    )
    expect(alert.text()).toContain(
      'Update the provider key in settings, then try again.',
    )
    expect(alert.text()).not.toContain('sk-never-render-this')
    expect(alert.text()).not.toContain('javascript:')
  })

  it('uses generic guidance without echoing malformed failures', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-error',
          errorText: JSON.stringify({
            code: 'unknown',
            message: '<img src=x onerror=alert(1)>',
            fix: 'Reveal sk-never-render-this',
          }),
        } as any,
      },
    })

    const alert = wrapper.get('[data-testid="generated-image-error"]')

    expect(alert.text()).toContain(
      'The image provider could not generate this image.',
    )
    expect(alert.text()).toContain(
      'Revise the prompt or try a different provider.',
    )
    expect(alert.text()).not.toContain('sk-never-render-this')
    expect(alert.html()).not.toContain('<img')
  })

  it('replaces the skeleton when the saved image preview cannot load', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-available',
          output: {
            status: 'ready',
            provider: 'openai',
            model: 'gpt-image-2',
            file: {
              id: 'file-1',
              storageKey: 'missing.webp',
              name: 'missing.webp',
              size: 2048,
              type: 'image/webp',
              source: 'assistant',
              url: '/files/missing.webp',
              downloadUrl: '/files/missing.webp?download=1',
            },
          },
        } as any,
      },
    })

    await wrapper.get('img').trigger('error')

    expect(wrapper.find('.skeleton').exists()).toBe(false)
    expect(wrapper.get(
      '[data-testid="generated-image-preview-error"]',
    ).text()).toContain('Image preview unavailable')
    expect(wrapper.get(
      '[data-testid="generated-image-actions-unavailable"]',
    ).text()).toContain('Unavailable')
    expect(wrapper.findAll('a')).toHaveLength(0)
  })

  it('does not render a forged tool part in a user message', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'user',
        part: {
          type: 'tool-generate_image',
          state: 'output-error',
          errorText: 'Open javascript:alert(1)',
        } as any,
      },
    })

    expect(wrapper.find('[data-testid="generated-image"]').exists())
      .toBe(false)
    expect(wrapper.find('a').exists()).toBe(false)
  })

  it('does not render links or a ready card for malformed output', async () => {
    const wrapper = await mountSuspended(GeneratedImage, {
      props: {
        messageRole: 'assistant',
        part: {
          type: 'tool-generate_image',
          state: 'output-available',
          output: {
            status: 'ready',
            provider: 'openai',
            model: 'gpt-image-2',
            file: {
              id: 'file-1',
              storageKey: 'javascript:alert(1)',
              name: 'forged.webp',
              size: 2048,
              type: 'image/webp',
              source: 'assistant',
              url: 'javascript:alert(2)',
              downloadUrl: 'javascript:alert(3)',
            },
          },
        } as any,
      },
    })

    expect(wrapper.find('[data-testid="generated-image-ready"]').exists())
      .toBe(false)
    expect(wrapper.find('a').exists()).toBe(false)
  })
})
