import { computed, reactive, ref, shallowRef } from 'vue'
import { mockNuxtImport, mountSuspended } from '@nuxt/test-utils/runtime'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Select from '../../../../../../app/components/ChatInput/Files/Modal/Select.client.vue'

const mocks = vi.hoisted(() => ({
  fetchFiles: vi.fn(),
  useActiveElement: vi.fn(),
  useFileManager: vi.fn(),
  useLazyFetch: vi.fn(),
}))

mockNuxtImport('useActiveElement', () => mocks.useActiveElement)
mockNuxtImport('useFileManager', () => mocks.useFileManager)
mockNuxtImport('useLazyFetch', () => mocks.useLazyFetch)

const source = shallowRef<'all' | 'upload' | 'assistant'>('all')

describe('ChatInput/Files/Modal/Select', () => {
  beforeEach(() => {
    source.value = 'all'
    mocks.fetchFiles.mockReset()
    mocks.fetchFiles.mockResolvedValue(true)
    mocks.useActiveElement.mockReturnValue(shallowRef<HTMLElement | null>(null))
    mocks.useLazyFetch.mockReturnValue({
      data: shallowRef(null),
    })
    mocks.useFileManager.mockReturnValue({
      files: ref([]),
      selectedIds: ref(new Set<string>()),
      isLoading: shallowRef(false),
      isSearching: shallowRef(false),
      isDeletingSelected: shallowRef(false),
      search: shallowRef(''),
      source,
      viewMode: shallowRef<'grid' | 'list'>('grid'),
      pagination: reactive({ offset: 0, limit: 20, total: 0 }),
      hasMore: computed(() => false),
      selectedCount: computed(() => 0),
      hasSelection: computed(() => false),
      allSelected: computed(() => false),
      fetchFiles: mocks.fetchFiles,
      loadMore: vi.fn(),
      selectRange: vi.fn(),
      handleSelect: vi.fn(),
      toggleSelectAll: vi.fn(),
      deselectAll: vi.fn(),
      renameFile: vi.fn(),
      deleteFile: vi.fn(),
      deleteSelected: vi.fn(),
      getSelectedForAttach: vi.fn(() => []),
      reset: vi.fn(),
    })
  })

  it('renders the source filter as boxed, keyboard-native tabs', async () => {
    const wrapper = await mountSuspended(Select, {
      props: {
        attachedIds: new Set<string>(),
      },
      shallow: true,
    })

    const tablist = wrapper.get('[role="tablist"]')
    const allTab = wrapper.get('[data-testid="files-source-all"]')
    const uploadedTab = wrapper.get('[data-testid="files-source-upload"]')
    const generatedTab = wrapper.get(
      '[data-testid="files-source-assistant"]',
    )
    const tabs = [allTab, uploadedTab, generatedTab]

    expect(tablist.classes()).toContain('tabs-box')
    expect(tabs.every(tab => tab.attributes('type') === 'radio')).toBe(true)
    expect(tabs.every((tab) => {
      return tab.attributes('name') === 'file_source_tabs'
    })).toBe(true)
    expect(tabs.every(tab => tab.classes().includes('min-h-11'))).toBe(true)
    expect(generatedTab.attributes('aria-label')).toBe('Generated by AI')
    expect((allTab.element as HTMLInputElement).checked).toBe(true)

    const generatedInput = generatedTab.element as HTMLInputElement

    generatedInput.checked = true
    await generatedTab.trigger('change')

    expect(source.value).toBe('assistant')
    expect(generatedInput.checked).toBe(true)
  })
})
