name: Deploy the project to Cloudflare Workers

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: "Update PR"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Update PR data
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { updatePR } = await import(
              '${{ github.workspace }}/.github/scripts/pr.ts'
            )

            await updatePR()

  build:
    uses: ./.github/workflows/build.yml
    
  comment:
    name: "Comment preview URL on PR"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Comment preview URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { displayPreviewUrl } = await import(
              '${{ github.workspace }}/.github/scripts/preview.ts'
            )

            await displayPreviewUrl()
        env:
          DEPLOYMENT_URL: ${{ needs.build.outputs.url }}